name = "nikitaporwal-worker"
account_id = "dedcb339ae411669d19772f5d3243f35"
main = "src/index.ts"
compatibility_date = "2024-02-24"

[[d1_databases]]
binding = "DB"
database_name = "mentoria-db"
database_id = "a6b41b43-e530-4348-a208-1eb7b7b7fff9"
