name = "nikitaporwal-worker"
account_id = "aa4372054b04b9e122c8f7ae701b207fe"
main = "src/index.ts"
compatibility_date = "2024-02-24"
[[d1_databases]]
binding = "DB"
database_name = "nikita-contacts"
database_id = "fae6ee3f-20ba-4775-94de-ca0a9850756d"
